import type { Metadata } from "next";
import "./globals.css";
import Theme from "@/theme";
import MainLayout from "@/layouts/MainLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body>
        <Theme>
          <MainLayout>
            {children}
          </MainLayout>
        </Theme>
      </body>
    </html>
  );
}
